# Generated by Django 5.0.7 on 2024-09-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_expensereport_myformdata_expensedetail_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('your_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('package_date', models.DateTimeField()),
                ('sales_order', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('order_quantity', models.PositiveIntegerField()),
                ('shipped_quantity', models.PositiveIntegerField()),
                ('package_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.packagereport')),
            ],
        ),
    ]
