# Generated by Django 5.0.7 on 2024-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
